// Frozen copy for formal verification. Source: risc-q/src/riscq/soc/rf/WaveWordBridge.scala
// (identical on branches waveword-bridge 6839f648 and claude-newdesign 708f2da5), generated by
// riscq.soc.rf.WaveWordBridgeGen 32 with WaveWordBridgeParams(leadTime = 32): the value QickGenParams
// uses on claude-newdesign. Queue depth 8, 32-bit time.
// Generator : SpinalHDL v1.14.2    git head : 61057ad2f62a36013885fc2075960d52d89af310
// Component : WaveWordBridge
// Git hash  : 6839f64838bbdab15c5ceb5fb6127a2772bb25d6

`timescale 1ns/1ps

module WaveWordBridge (
  input  wire          io_cmd_valid,
  input  wire [15:0]   io_cmd_payload_address,
  input  wire [31:0]   io_cmd_payload_data,
  input  wire [31:0]   io_time,
  output wire          io_wave_valid,
  input  wire          io_wave_ready,
  output wire [167:0]  io_wave_payload,
  output wire          io_trig,
  input  wire          clk,
  input  wire          reset
);

  wire                q_io_push_ready;
  wire                q_io_pop_valid;
  wire       [167:0]  q_io_pop_payload;
  wire                tq_io_push_ready;
  wire                tq_io_pop_valid;
  wire       [15:0]   tq_io_pop_payload;
  reg        [31:0]   freq;
  reg        [31:0]   phase;
  reg        [23:0]   env;
  reg        [31:0]   gain;
  reg        [31:0]   nsamp;
  reg        [15:0]   conf;
  reg        [31:0]   startTime;
  wire                when_WaveWordBridge_l58;
  wire                when_WaveWordBridge_l59;
  wire                when_WaveWordBridge_l60;
  wire                when_WaveWordBridge_l61;
  wire                when_WaveWordBridge_l62;
  wire                when_WaveWordBridge_l63;
  wire                when_WaveWordBridge_l64;
  wire                fire;
  reg        [31:0]   trigTime;
  reg        [15:0]   width;
  wire                when_WaveWordBridge_l72;
  wire                when_WaveWordBridge_l73;
  wire                fireTrig;
  reg        [167:0]  word;
  reg        [15:0]   cnt;
  reg                 trig;
  wire                when_WaveWordBridge_l109;
  wire                when_WaveWordBridge_l110;

  TimedQueue q (
    .io_time                   (io_time[31:0]          ), //i
    .io_push_valid             (fire                   ), //i
    .io_push_ready             (q_io_push_ready        ), //o
    .io_push_payload_data      (word[167:0]            ), //i
    .io_push_payload_startTime (startTime[31:0]        ), //i
    .io_pop_valid              (q_io_pop_valid         ), //o
    .io_pop_payload            (q_io_pop_payload[167:0]), //o
    .clk                       (clk                    ), //i
    .reset                     (reset                  )  //i
  );
  TimedQueue_1 tq (
    .io_time                   (io_time[31:0]          ), //i
    .io_push_valid             (fireTrig               ), //i
    .io_push_ready             (tq_io_push_ready       ), //o
    .io_push_payload_data      (width[15:0]            ), //i
    .io_push_payload_startTime (trigTime[31:0]         ), //i
    .io_pop_valid              (tq_io_pop_valid        ), //o
    .io_pop_payload            (tq_io_pop_payload[15:0]), //o
    .clk                       (clk                    ), //i
    .reset                     (reset                  )  //i
  );
  assign when_WaveWordBridge_l58 = (io_cmd_valid && (io_cmd_payload_address == 16'h0));
  assign when_WaveWordBridge_l59 = (io_cmd_valid && (io_cmd_payload_address == 16'h0004));
  assign when_WaveWordBridge_l60 = (io_cmd_valid && (io_cmd_payload_address == 16'h0008));
  assign when_WaveWordBridge_l61 = (io_cmd_valid && (io_cmd_payload_address == 16'h000c));
  assign when_WaveWordBridge_l62 = (io_cmd_valid && (io_cmd_payload_address == 16'h0010));
  assign when_WaveWordBridge_l63 = (io_cmd_valid && (io_cmd_payload_address == 16'h0014));
  assign when_WaveWordBridge_l64 = (io_cmd_valid && (io_cmd_payload_address == 16'h0018));
  assign fire = (io_cmd_valid && (io_cmd_payload_address == 16'h001c));
  assign when_WaveWordBridge_l72 = (io_cmd_valid && (io_cmd_payload_address == 16'h0020));
  assign when_WaveWordBridge_l73 = (io_cmd_valid && (io_cmd_payload_address == 16'h0024));
  assign fireTrig = (io_cmd_valid && (io_cmd_payload_address == 16'h0028));
  always @(*) begin
    word[31 : 0] = freq;
    word[63 : 32] = phase;
    word[87 : 64] = env;
    word[119 : 88] = gain;
    word[151 : 120] = nsamp;
    word[167 : 152] = conf;
  end

  assign io_wave_valid = q_io_pop_valid;
  assign io_wave_payload = q_io_pop_payload;
  assign when_WaveWordBridge_l109 = (cnt != 16'h0);
  assign when_WaveWordBridge_l110 = (cnt == 16'h0001);
  assign io_trig = trig;
  always @(posedge clk or posedge reset) begin
    if(reset) begin
      freq <= 32'h0;
      phase <= 32'h0;
      env <= 24'h0;
      gain <= 32'h0;
      nsamp <= 32'h0;
      conf <= 16'h0;
      startTime <= 32'h0;
      trigTime <= 32'h0;
      width <= 16'h0;
      cnt <= 16'h0;
      trig <= 1'b0;
    end else begin
      if(when_WaveWordBridge_l58) begin
        freq <= io_cmd_payload_data;
      end
      if(when_WaveWordBridge_l59) begin
        phase <= io_cmd_payload_data;
      end
      if(when_WaveWordBridge_l60) begin
        env <= io_cmd_payload_data[23 : 0];
      end
      if(when_WaveWordBridge_l61) begin
        gain <= io_cmd_payload_data;
      end
      if(when_WaveWordBridge_l62) begin
        nsamp <= io_cmd_payload_data;
      end
      if(when_WaveWordBridge_l63) begin
        conf <= io_cmd_payload_data[15 : 0];
      end
      if(when_WaveWordBridge_l64) begin
        startTime <= io_cmd_payload_data[31 : 0];
      end
      if(when_WaveWordBridge_l72) begin
        trigTime <= io_cmd_payload_data[31 : 0];
      end
      if(when_WaveWordBridge_l73) begin
        width <= io_cmd_payload_data[15 : 0];
      end
      if(tq_io_pop_valid) begin
        trig <= 1'b1;
        cnt <= tq_io_pop_payload;
      end
      if(when_WaveWordBridge_l109) begin
        cnt <= (cnt - 16'h0001);
      end
      if(when_WaveWordBridge_l110) begin
        trig <= 1'b0;
      end
    end
  end


endmodule

module TimedQueue_1 (
  input  wire [31:0]   io_time,
  input  wire          io_push_valid,
  output wire          io_push_ready,
  input  wire [15:0]   io_push_payload_data,
  input  wire [31:0]   io_push_payload_startTime,
  output wire          io_pop_valid,
  output wire [15:0]   io_pop_payload,
  input  wire          clk,
  input  wire          reset
);

  reg                 logic_fifo_io_pop_ready;
  wire                logic_fifo_io_push_ready;
  wire                logic_fifo_io_pop_valid;
  wire       [15:0]   logic_fifo_io_pop_payload_data;
  wire       [31:0]   logic_fifo_io_pop_payload_startTime;
  wire       [3:0]    logic_fifo_io_occupancy;
  wire       [3:0]    logic_fifo_io_availability;
  wire       [31:0]   _zz_logic_due;
  wire       [31:0]   _zz_logic_due_1;
  wire       [31:0]   leadC1;
  wire                logic_head_valid;
  wire                logic_head_ready;
  wire       [15:0]   logic_head_payload_data;
  wire       [31:0]   logic_head_payload_startTime;
  reg                 logic_fifo_io_pop_rValid;
  reg        [15:0]   logic_fifo_io_pop_rData_data;
  reg        [31:0]   logic_fifo_io_pop_rData_startTime;
  wire                when_Stream_l477;
  wire                logic_due;
  reg                 _zz_io_pop_valid;
  reg                 io_pop_valid_regNext;

  assign _zz_logic_due = (_zz_logic_due_1 - logic_head_payload_startTime);
  assign _zz_logic_due_1 = (io_time + leadC1);
  StreamFifo_1 logic_fifo (
    .io_push_valid             (io_push_valid                            ), //i
    .io_push_ready             (logic_fifo_io_push_ready                 ), //o
    .io_push_payload_data      (io_push_payload_data[15:0]               ), //i
    .io_push_payload_startTime (io_push_payload_startTime[31:0]          ), //i
    .io_pop_valid              (logic_fifo_io_pop_valid                  ), //o
    .io_pop_ready              (logic_fifo_io_pop_ready                  ), //i
    .io_pop_payload_data       (logic_fifo_io_pop_payload_data[15:0]     ), //o
    .io_pop_payload_startTime  (logic_fifo_io_pop_payload_startTime[31:0]), //o
    .io_flush                  (1'b0                                     ), //i
    .io_occupancy              (logic_fifo_io_occupancy[3:0]             ), //o
    .io_availability           (logic_fifo_io_availability[3:0]          ), //o
    .clk                       (clk                                      ), //i
    .reset                     (reset                                    )  //i
  );
  assign leadC1 = 32'h00000009;
  assign io_push_ready = logic_fifo_io_push_ready;
  always @(*) begin
    logic_fifo_io_pop_ready = logic_head_ready;
    if(when_Stream_l477) begin
      logic_fifo_io_pop_ready = 1'b1;
    end
  end

  assign when_Stream_l477 = (! logic_head_valid);
  assign logic_head_valid = logic_fifo_io_pop_rValid;
  assign logic_head_payload_data = logic_fifo_io_pop_rData_data;
  assign logic_head_payload_startTime = logic_fifo_io_pop_rData_startTime;
  assign logic_due = (! _zz_logic_due[31]);
  assign io_pop_valid = (_zz_io_pop_valid && (! io_pop_valid_regNext));
  assign io_pop_payload = logic_head_payload_data;
  assign logic_head_ready = io_pop_valid;
  always @(posedge clk or posedge reset) begin
    if(reset) begin
      logic_fifo_io_pop_rValid <= 1'b0;
      _zz_io_pop_valid <= 1'b0;
      io_pop_valid_regNext <= 1'b0;
    end else begin
      if(logic_fifo_io_pop_ready) begin
        logic_fifo_io_pop_rValid <= logic_fifo_io_pop_valid;
      end
      _zz_io_pop_valid <= (logic_head_valid && logic_due);
      io_pop_valid_regNext <= io_pop_valid;
    end
  end

  always @(posedge clk) begin
    if(logic_fifo_io_pop_ready) begin
      logic_fifo_io_pop_rData_data <= logic_fifo_io_pop_payload_data;
      logic_fifo_io_pop_rData_startTime <= logic_fifo_io_pop_payload_startTime;
    end
  end


endmodule

module TimedQueue (
  input  wire [31:0]   io_time,
  input  wire          io_push_valid,
  output wire          io_push_ready,
  input  wire [167:0]  io_push_payload_data,
  input  wire [31:0]   io_push_payload_startTime,
  output wire          io_pop_valid,
  output wire [167:0]  io_pop_payload,
  input  wire          clk,
  input  wire          reset
);

  reg                 logic_fifo_io_pop_ready;
  wire                logic_fifo_io_push_ready;
  wire                logic_fifo_io_pop_valid;
  wire       [167:0]  logic_fifo_io_pop_payload_data;
  wire       [31:0]   logic_fifo_io_pop_payload_startTime;
  wire       [3:0]    logic_fifo_io_occupancy;
  wire       [3:0]    logic_fifo_io_availability;
  wire       [31:0]   _zz_logic_due;
  wire       [31:0]   _zz_logic_due_1;
  wire       [31:0]   leadC1;
  wire                logic_head_valid;
  wire                logic_head_ready;
  wire       [167:0]  logic_head_payload_data;
  wire       [31:0]   logic_head_payload_startTime;
  reg                 logic_fifo_io_pop_rValid;
  reg        [167:0]  logic_fifo_io_pop_rData_data;
  reg        [31:0]   logic_fifo_io_pop_rData_startTime;
  wire                when_Stream_l477;
  wire                logic_due;
  reg                 _zz_io_pop_valid;
  reg                 io_pop_valid_regNext;

  assign _zz_logic_due = (_zz_logic_due_1 - logic_head_payload_startTime);
  assign _zz_logic_due_1 = (io_time + leadC1);
  StreamFifo logic_fifo (
    .io_push_valid             (io_push_valid                            ), //i
    .io_push_ready             (logic_fifo_io_push_ready                 ), //o
    .io_push_payload_data      (io_push_payload_data[167:0]              ), //i
    .io_push_payload_startTime (io_push_payload_startTime[31:0]          ), //i
    .io_pop_valid              (logic_fifo_io_pop_valid                  ), //o
    .io_pop_ready              (logic_fifo_io_pop_ready                  ), //i
    .io_pop_payload_data       (logic_fifo_io_pop_payload_data[167:0]    ), //o
    .io_pop_payload_startTime  (logic_fifo_io_pop_payload_startTime[31:0]), //o
    .io_flush                  (1'b0                                     ), //i
    .io_occupancy              (logic_fifo_io_occupancy[3:0]             ), //o
    .io_availability           (logic_fifo_io_availability[3:0]          ), //o
    .clk                       (clk                                      ), //i
    .reset                     (reset                                    )  //i
  );
  assign leadC1 = 32'h00000021;
  assign io_push_ready = logic_fifo_io_push_ready;
  always @(*) begin
    logic_fifo_io_pop_ready = logic_head_ready;
    if(when_Stream_l477) begin
      logic_fifo_io_pop_ready = 1'b1;
    end
  end

  assign when_Stream_l477 = (! logic_head_valid);
  assign logic_head_valid = logic_fifo_io_pop_rValid;
  assign logic_head_payload_data = logic_fifo_io_pop_rData_data;
  assign logic_head_payload_startTime = logic_fifo_io_pop_rData_startTime;
  assign logic_due = (! _zz_logic_due[31]);
  assign io_pop_valid = (_zz_io_pop_valid && (! io_pop_valid_regNext));
  assign io_pop_payload = logic_head_payload_data;
  assign logic_head_ready = io_pop_valid;
  always @(posedge clk or posedge reset) begin
    if(reset) begin
      logic_fifo_io_pop_rValid <= 1'b0;
      _zz_io_pop_valid <= 1'b0;
      io_pop_valid_regNext <= 1'b0;
    end else begin
      if(logic_fifo_io_pop_ready) begin
        logic_fifo_io_pop_rValid <= logic_fifo_io_pop_valid;
      end
      _zz_io_pop_valid <= (logic_head_valid && logic_due);
      io_pop_valid_regNext <= io_pop_valid;
    end
  end

  always @(posedge clk) begin
    if(logic_fifo_io_pop_ready) begin
      logic_fifo_io_pop_rData_data <= logic_fifo_io_pop_payload_data;
      logic_fifo_io_pop_rData_startTime <= logic_fifo_io_pop_payload_startTime;
    end
  end


endmodule

module StreamFifo_1 (
  input  wire          io_push_valid,
  output wire          io_push_ready,
  input  wire [15:0]   io_push_payload_data,
  input  wire [31:0]   io_push_payload_startTime,
  output wire          io_pop_valid,
  input  wire          io_pop_ready,
  output wire [15:0]   io_pop_payload_data,
  output wire [31:0]   io_pop_payload_startTime,
  input  wire          io_flush,
  output wire [3:0]    io_occupancy,
  output wire [3:0]    io_availability,
  input  wire          clk,
  input  wire          reset
);

  wire       [47:0]   logic_ram_spinal_port1;
  wire       [47:0]   _zz_logic_ram_port;
  reg                 _zz_1;
  wire                logic_ptr_doPush;
  wire                logic_ptr_doPop;
  wire                logic_ptr_full;
  wire                logic_ptr_empty;
  reg        [3:0]    logic_ptr_push;
  reg        [3:0]    logic_ptr_pop;
  wire       [3:0]    logic_ptr_occupancy;
  wire       [3:0]    logic_ptr_popOnIo;
  wire                when_Stream_l1557;
  reg                 logic_ptr_wentUp;
  wire                io_push_fire;
  wire                logic_push_onRam_write_valid;
  wire       [2:0]    logic_push_onRam_write_payload_address;
  wire       [15:0]   logic_push_onRam_write_payload_data_data;
  wire       [31:0]   logic_push_onRam_write_payload_data_startTime;
  wire                logic_pop_addressGen_valid;
  wire                logic_pop_addressGen_ready;
  wire       [2:0]    logic_pop_addressGen_payload;
  wire                logic_pop_addressGen_fire;
  wire       [15:0]   logic_pop_async_readed_data;
  wire       [31:0]   logic_pop_async_readed_startTime;
  wire       [47:0]   _zz_logic_pop_async_readed_data;
  wire                logic_pop_addressGen_translated_valid;
  wire                logic_pop_addressGen_translated_ready;
  wire       [15:0]   logic_pop_addressGen_translated_payload_data;
  wire       [31:0]   logic_pop_addressGen_translated_payload_startTime;
  (* ram_style = "distributed" *) reg [47:0] logic_ram [0:7];

  assign _zz_logic_ram_port = {logic_push_onRam_write_payload_data_startTime,logic_push_onRam_write_payload_data_data};
  always @(posedge clk) begin
    if(_zz_1) begin
      logic_ram[logic_push_onRam_write_payload_address] <= _zz_logic_ram_port;
    end
  end

  assign logic_ram_spinal_port1 = logic_ram[logic_pop_addressGen_payload];
  always @(*) begin
    _zz_1 = 1'b0;
    if(logic_push_onRam_write_valid) begin
      _zz_1 = 1'b1;
    end
  end

  assign when_Stream_l1557 = (logic_ptr_doPush != logic_ptr_doPop);
  assign logic_ptr_full = (((logic_ptr_push ^ logic_ptr_popOnIo) ^ 4'b1000) == 4'b0000);
  assign logic_ptr_empty = (logic_ptr_push == logic_ptr_pop);
  assign logic_ptr_occupancy = (logic_ptr_push - logic_ptr_popOnIo);
  assign io_push_ready = (! logic_ptr_full);
  assign io_push_fire = (io_push_valid && io_push_ready);
  assign logic_ptr_doPush = io_push_fire;
  assign logic_push_onRam_write_valid = io_push_fire;
  assign logic_push_onRam_write_payload_address = logic_ptr_push[2:0];
  assign logic_push_onRam_write_payload_data_data = io_push_payload_data;
  assign logic_push_onRam_write_payload_data_startTime = io_push_payload_startTime;
  assign logic_pop_addressGen_valid = (! logic_ptr_empty);
  assign logic_pop_addressGen_payload = logic_ptr_pop[2:0];
  assign logic_pop_addressGen_fire = (logic_pop_addressGen_valid && logic_pop_addressGen_ready);
  assign logic_ptr_doPop = logic_pop_addressGen_fire;
  assign _zz_logic_pop_async_readed_data = logic_ram_spinal_port1;
  assign logic_pop_async_readed_data = _zz_logic_pop_async_readed_data[15 : 0];
  assign logic_pop_async_readed_startTime = _zz_logic_pop_async_readed_data[47 : 16];
  assign logic_pop_addressGen_translated_valid = logic_pop_addressGen_valid;
  assign logic_pop_addressGen_ready = logic_pop_addressGen_translated_ready;
  assign logic_pop_addressGen_translated_payload_data = logic_pop_async_readed_data;
  assign logic_pop_addressGen_translated_payload_startTime = logic_pop_async_readed_startTime;
  assign io_pop_valid = logic_pop_addressGen_translated_valid;
  assign logic_pop_addressGen_translated_ready = io_pop_ready;
  assign io_pop_payload_data = logic_pop_addressGen_translated_payload_data;
  assign io_pop_payload_startTime = logic_pop_addressGen_translated_payload_startTime;
  assign logic_ptr_popOnIo = logic_ptr_pop;
  assign io_occupancy = logic_ptr_occupancy;
  assign io_availability = (4'b1000 - logic_ptr_occupancy);
  always @(posedge clk or posedge reset) begin
    if(reset) begin
      logic_ptr_push <= 4'b0000;
      logic_ptr_pop <= 4'b0000;
      logic_ptr_wentUp <= 1'b0;
    end else begin
      if(when_Stream_l1557) begin
        logic_ptr_wentUp <= logic_ptr_doPush;
      end
      if(io_flush) begin
        logic_ptr_wentUp <= 1'b0;
      end
      if(logic_ptr_doPush) begin
        logic_ptr_push <= (logic_ptr_push + 4'b0001);
      end
      if(logic_ptr_doPop) begin
        logic_ptr_pop <= (logic_ptr_pop + 4'b0001);
      end
      if(io_flush) begin
        logic_ptr_push <= 4'b0000;
        logic_ptr_pop <= 4'b0000;
      end
    end
  end


endmodule

module StreamFifo (
  input  wire          io_push_valid,
  output wire          io_push_ready,
  input  wire [167:0]  io_push_payload_data,
  input  wire [31:0]   io_push_payload_startTime,
  output wire          io_pop_valid,
  input  wire          io_pop_ready,
  output wire [167:0]  io_pop_payload_data,
  output wire [31:0]   io_pop_payload_startTime,
  input  wire          io_flush,
  output wire [3:0]    io_occupancy,
  output wire [3:0]    io_availability,
  input  wire          clk,
  input  wire          reset
);

  wire       [199:0]  logic_ram_spinal_port1;
  wire       [199:0]  _zz_logic_ram_port;
  reg                 _zz_1;
  wire                logic_ptr_doPush;
  wire                logic_ptr_doPop;
  wire                logic_ptr_full;
  wire                logic_ptr_empty;
  reg        [3:0]    logic_ptr_push;
  reg        [3:0]    logic_ptr_pop;
  wire       [3:0]    logic_ptr_occupancy;
  wire       [3:0]    logic_ptr_popOnIo;
  wire                when_Stream_l1557;
  reg                 logic_ptr_wentUp;
  wire                io_push_fire;
  wire                logic_push_onRam_write_valid;
  wire       [2:0]    logic_push_onRam_write_payload_address;
  wire       [167:0]  logic_push_onRam_write_payload_data_data;
  wire       [31:0]   logic_push_onRam_write_payload_data_startTime;
  wire                logic_pop_addressGen_valid;
  wire                logic_pop_addressGen_ready;
  wire       [2:0]    logic_pop_addressGen_payload;
  wire                logic_pop_addressGen_fire;
  wire       [167:0]  logic_pop_async_readed_data;
  wire       [31:0]   logic_pop_async_readed_startTime;
  wire       [199:0]  _zz_logic_pop_async_readed_data;
  wire                logic_pop_addressGen_translated_valid;
  wire                logic_pop_addressGen_translated_ready;
  wire       [167:0]  logic_pop_addressGen_translated_payload_data;
  wire       [31:0]   logic_pop_addressGen_translated_payload_startTime;
  (* ram_style = "distributed" *) reg [199:0] logic_ram [0:7];

  assign _zz_logic_ram_port = {logic_push_onRam_write_payload_data_startTime,logic_push_onRam_write_payload_data_data};
  always @(posedge clk) begin
    if(_zz_1) begin
      logic_ram[logic_push_onRam_write_payload_address] <= _zz_logic_ram_port;
    end
  end

  assign logic_ram_spinal_port1 = logic_ram[logic_pop_addressGen_payload];
  always @(*) begin
    _zz_1 = 1'b0;
    if(logic_push_onRam_write_valid) begin
      _zz_1 = 1'b1;
    end
  end

  assign when_Stream_l1557 = (logic_ptr_doPush != logic_ptr_doPop);
  assign logic_ptr_full = (((logic_ptr_push ^ logic_ptr_popOnIo) ^ 4'b1000) == 4'b0000);
  assign logic_ptr_empty = (logic_ptr_push == logic_ptr_pop);
  assign logic_ptr_occupancy = (logic_ptr_push - logic_ptr_popOnIo);
  assign io_push_ready = (! logic_ptr_full);
  assign io_push_fire = (io_push_valid && io_push_ready);
  assign logic_ptr_doPush = io_push_fire;
  assign logic_push_onRam_write_valid = io_push_fire;
  assign logic_push_onRam_write_payload_address = logic_ptr_push[2:0];
  assign logic_push_onRam_write_payload_data_data = io_push_payload_data;
  assign logic_push_onRam_write_payload_data_startTime = io_push_payload_startTime;
  assign logic_pop_addressGen_valid = (! logic_ptr_empty);
  assign logic_pop_addressGen_payload = logic_ptr_pop[2:0];
  assign logic_pop_addressGen_fire = (logic_pop_addressGen_valid && logic_pop_addressGen_ready);
  assign logic_ptr_doPop = logic_pop_addressGen_fire;
  assign _zz_logic_pop_async_readed_data = logic_ram_spinal_port1;
  assign logic_pop_async_readed_data = _zz_logic_pop_async_readed_data[167 : 0];
  assign logic_pop_async_readed_startTime = _zz_logic_pop_async_readed_data[199 : 168];
  assign logic_pop_addressGen_translated_valid = logic_pop_addressGen_valid;
  assign logic_pop_addressGen_ready = logic_pop_addressGen_translated_ready;
  assign logic_pop_addressGen_translated_payload_data = logic_pop_async_readed_data;
  assign logic_pop_addressGen_translated_payload_startTime = logic_pop_async_readed_startTime;
  assign io_pop_valid = logic_pop_addressGen_translated_valid;
  assign logic_pop_addressGen_translated_ready = io_pop_ready;
  assign io_pop_payload_data = logic_pop_addressGen_translated_payload_data;
  assign io_pop_payload_startTime = logic_pop_addressGen_translated_payload_startTime;
  assign logic_ptr_popOnIo = logic_ptr_pop;
  assign io_occupancy = logic_ptr_occupancy;
  assign io_availability = (4'b1000 - logic_ptr_occupancy);
  always @(posedge clk or posedge reset) begin
    if(reset) begin
      logic_ptr_push <= 4'b0000;
      logic_ptr_pop <= 4'b0000;
      logic_ptr_wentUp <= 1'b0;
    end else begin
      if(when_Stream_l1557) begin
        logic_ptr_wentUp <= logic_ptr_doPush;
      end
      if(io_flush) begin
        logic_ptr_wentUp <= 1'b0;
      end
      if(logic_ptr_doPush) begin
        logic_ptr_push <= (logic_ptr_push + 4'b0001);
      end
      if(logic_ptr_doPop) begin
        logic_ptr_pop <= (logic_ptr_pop + 4'b0001);
      end
      if(io_flush) begin
        logic_ptr_push <= 4'b0000;
        logic_ptr_pop <= 4'b0000;
      end
    end
  end


endmodule
